apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devopstic.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "devopstic.name" . }}-grafana
    helm.sh/chart: {{ include "devopstic.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devopstic.name" . }}-grafana
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devopstic.name" . }}-grafana
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: data-grafana
          persistentVolumeClaim:
            claimName: data-pvc-{{ include "devopstic.name" . }}-grafana
      containers:
        - name: grafana
          image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          volumeMounts:
            - name: data-grafana
              mountPath: /var/lib/grafana
          ports:
            - name: grafana
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: grafana
          readinessProbe:
            httpGet:
              path: /
              port: grafana
          env:
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"
            - name: GF_USERS_ALLOW_ORG_CREATE
              value: "false"
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
